### ISSUE TITLE
SpecificCodeCPP in Models_2D/Polyfunctional.py

### ISSUE THREAD

**Issue by temudschin** [zunzun/pyeq2#1]
First of all, thanks for this great code! It helps me a lot.

I encountered a small error in Polyfuncitonal.py -> function SpecificCodecCPP.

After running FitAllEquationsInParallelUsingQueues_LargeResultList_2D.py I tried to get the CPP Code of the UserSelectablePolyfunctional, but it complains, that self._coefficientDesignators is unknown, so I added a line:

self._coefficientDesignators = self.GetCoefficientDesignators()

at the beginning of the function SpecificCodecCPP in UserSelectablePolyfunctional, that works and give the same output than GetDisplayHTML:

```
def SpecificCodeCPP(self):
    self._coefficientDesignators = self.GetCoefficientDesignators()
    s = ""
    count = 0
    for i in self.polyfunctional2DFlags:
        if i != 0:
            s += "\ttemp += " + self._coefficientDesignators[count] + " * " + self.polyfunctionalEquationList[i].CPP + ";\n"
            count += 1
    if 0 in self.polyfunctional2DFlags:
        s += "\ttemp += " + self._coefficientDesignators[count] + ";\n"

    return s
```

**Comment by zunzun** [comment]
I will investigate and reply, thank you for letting me know.

James

**Comment by zunzun** [comment]
This was correct in the 3D version and not the 2D version of the file.  Now corrected, and thank you kindly for letting me know.

James
